apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-feed-deloitte-api
  labels:
    app: events-feed-deloitte-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events-feed-deloitte-api
  template:
    metadata:
      labels:
        app: events-feed-deloitte-api
    spec:
      containers:
      - name: events-feed-deloitte-api
        image: monambigha/events-feed-backend:v1.0
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: "backend-server"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
---

apiVersion: v1
kind: Service
metadata: 
  name: events-feed-deloitte-api-svc
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 8080
  selector: 
    app: events-feed-deloitte-api
  type: LoadBalancer
---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: events-feed-deloitte-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: events-feed-deloitte-api
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60